In [1]:
import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load data
with open('point_metrics.json', 'r') as f:
    points_metrics = json.load(f)
with open('garch_metrics.json', 'r') as f:
    garch_metrics = json.load(f)

print("Points Metrics:", points_metrics)
print("GARCH Metrics:", garch_metrics)

Points Metrics: {'SARIMA (Tuned)': {'MAE': 0.7988613546566415, 'RMSE': 2.51389782494208, 'MAPE': 16.141396118070293}, 'Random Forest (Tuned)': {'MAE': 0.3969996858922311, 'RMSE': 2.0091456411209045, 'MAPE': 5.745239931818722}, 'XGBoost (Tuned)': {'MAE': 0.44224349380941946, 'RMSE': 2.071611045817551, 'MAPE': 6.914142411187278}, 'LSTM (Tuned)': {'MAE': 0.39625953473623504, 'RMSE': 1.8430451850380472, 'MAPE': 6.092601176651393}}
GARCH Metrics: {'GARCH(1,1)': {'Log-Likelihood': -5018.725184341471, 'AIC': 10045.450368682941, 'BIC': 10066.143135652888}}

In [3]:
sns.set_theme(style="whitegrid")

In [4]:
# Summarize dataframes
points_df = pd.DataFrame.from_dict(points_metrics, orient='index')
garch_df = pd.DataFrame.from_dict(garch_metrics, orient='index')
print("Point Forecast Models (Price Prediction)\n")
display(points_df)
print("GARCH DataFrame:\n")
display(garch_df)

Point Forecast Models (Price Prediction)

                            MAE      RMSE       MAPE
SARIMA (Tuned)         0.798861  2.513898  16.141396
Random Forest (Tuned)  0.397000  2.009146   5.745240
XGBoost (Tuned)        0.442243  2.071611   6.914142
LSTM (Tuned)           0.396260  1.843045   6.092601

GARCH DataFrame:

            Log-Likelihood           AIC           BIC
GARCH(1,1)    -5018.725184  10045.450369  10066.143136